{{- if .Values.gatewayNetworking.enabled }}

{{- if .Values.gatewayNetworking.httpsRoute }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}-https-route
spec:
  parentRefs:
    - name: {{ .Release.Namespace }}-wildcard-gateway
      namespace: {{ .Release.Namespace }}
      sectionName: {{ .Release.Namespace }}-https-listener
  hostnames:
{{- range index .Values.gatewayNetworking.httpsRoute.hostnames .Release.Namespace }}
    - {{ . }}
{{- end }}
  rules:
{{- range .Values.gatewayNetworking.httpsRoute.rules }}
    - matches:
      - path:
          type: PathPrefix
          value: {{ .pathPrefix }}
      backendRefs:
{{- range .backends }}
        - name: {{ $.Release.Name }}
          namespace: {{ $.Release.Namespace }}
          port: {{ .port }}
{{- end }}
{{- end }}
{{- end }}

---

{{- if .Values.gatewayNetworking.httpRedirect }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Namespace }}-http-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Release.Namespace }}-wildcard-gateway
      namespace: {{ .Release.Namespace }}
      sectionName: {{ .Release.Namespace }}-http-listener
  hostnames:
{{- range index .Values.gatewayNetworking.httpRedirect.hostnames .Release.Namespace }}
    - {{ . }}
{{- end }}
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: {{ .Values.gatewayNetworking.httpRedirect.redirect.scheme }}
          statusCode: {{ .Values.gatewayNetworking.httpRedirect.redirect.statusCode }}
{{- end }}

{{- end }}