{{- if .Values.gatewayNetworking.enabled }}

{{- if .Values.gatewayNetworking.httpsRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}-https-route
spec:
  parentRefs:
    - name: {{ .Release.Namespace }}-wildcard-gateway
      namespace: {{ .Release.Namespace }}
      sectionName: https-listener
  hostnames:
{{- range index .Values.gatewayNetworking.httpsRoute.hostnames .Release.Namespace }}
    - {{ . }}
{{- end }}
  rules:
{{- $ns := .Release.Namespace }}
{{- range $rule := index .Values.gatewayNetworking.httpsRoute.rules $ns }}
  - matches:
      - path:
          type: PathPrefix
          value: {{ $rule.pathPrefix }}
    backendRefs:
    {{- range $be := $rule.backends }}
      - name: {{ $be.name }}-{{ $.Chart.Name }}
        port: {{ $be.port }}
    {{- end }}
{{- end }}
{{- end }}

---

{{- if .Values.gatewayNetworking.httpRedirect.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Namespace }}-http-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Release.Namespace }}-wildcard-gateway
      namespace: {{ .Release.Namespace }}
      sectionName: http-listener
  hostnames:
{{- range index .Values.gatewayNetworking.httpRedirect.hostnames .Release.Namespace }}
    - {{ . }}
{{- end }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: {{ .Values.gatewayNetworking.httpRedirect.redirect.scheme }}
            statusCode: {{ .Values.gatewayNetworking.httpRedirect.redirect.statusCode }}
{{- end }}

{{- end }}
