{{- if .Values.Certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Namespace }}-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Namespace }}-tls-secret
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
{{- range .Values.Certificate.dnsNames }}
    - {{ . | quote }}
{{- end }}
{{- end }}