{{- if .Values.wildcardCertificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Namespace }}-wildcard-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Namespace }}-wildcard-tls-secret
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
{{- range .Values.wildcardCertificate.dnsNames }}
    - {{ . | quote }}
{{- end }}
{{- end }}